apiVersion: v1
kind: Service
metadata:
  name: invitation-paper
  namespace: invitation-paper
spec:
  type: NodePort
  selector:
    app: invitation-paper
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30081
